In [ ]:
#Assignment – Numpy

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [3]:
arr = np.random.randint(1,9,(3,3))
print(arr)

[[2 2 2]
 [7 7 4]
 [5 7 6]]


In [4]:
arr = np.array([[[1,2],[3,4],[5,6]]])
print('Dimension:',arr.ndim)
print('Shape:',arr.shape)
print('Size:',arr.size)
print('Data type:',arr.dtype)

Dimension: 3
Shape: (1, 3, 2)
Size: 6
Data type: int64


In [5]:
np.full((10),5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [23]:
arr = np.arange(10,30,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120],
                [130, 140, 150, 160]])

In [14]:
arr[2][1]

np.int64(100)

In [16]:
arr[0]

array([10, 20, 30, 40])

In [17]:
arr[:,-1]

array([ 40,  80, 120, 160])

In [18]:
arr[:2,:2]

array([[10, 20],
       [50, 60]])

In [19]:
arr[1:4,:2]

array([[ 50,  60],
       [ 90, 100],
       [130, 140]])

In [20]:
arr[0,1::2]

array([20, 40])

In [21]:
arr[(0,2,3),(1,3,0)]

array([ 20, 120, 130])

In [22]:
arr[2:,2:]

array([[110, 120],
       [150, 160]])