In [1]:
#NumPy: Funny TasK’s

In [2]:
import numpy as np

In [3]:
mat_size = int(input('Matrix size = '))

arr = np.zeros([mat_size,mat_size])
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr = arr.astype(int)
print(arr)

Matrix size =  10


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [4]:
i = int(input('Starting Range:'))
j = int(input('Ending Range:'))

arr = np.arange(i,j)
arr[arr%2==0] = 0
print(arr)

Starting Range: 1
Ending Range: 21


[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]


In [5]:
mat_size = int(input('Matrix size = '))
arr = np.zeros([mat_size,mat_size])
arr[0] = 1
arr[-1] = 1
arr[:,0] = 1
arr[:,-1] = 1
print(arr)

Matrix size =  5


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
list1 = [1,2,3,4,5,6]
arr = np.array(list1)

arr = arr.reshape(3,2)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
arr = np.random.randint(1,100,10)
print('Original array:')
print(arr)
maxi = np.max(arr)
print('Maximum Value:',maxi)
index = np.argmax(arr)
print('Index:', index)

Original array:
[ 8 41 86 38 38 65  2 68 20 11]
Maximum Value: 86
Index: 2


In [8]:
list1 = [1,2,3,4,5,6,7,8,9]
arr = np.array(list1).reshape(3,3)
print('Original array:')
print(arr)
print()
print('Mean:',np.mean(arr))

maxi = np.max(arr)
print('Maximum value:',maxi)
index = np.argmax(arr)
print('Index of the maximum value:',index)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean: 5.0
Maximum value: 9
Index of the maximum value: 8
