In [1]:
#Numpy 

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

arr2 = np.array(['one', 'two', 'three', 'four','five'])

print('1-D array with numbers:',arr1)
print('1-D array with strings:',arr2)

1-D array with numbers: [1 2 3 4 5]
1-D array with strings: ['one' 'two' 'three' 'four' 'five']


In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])
print('1st Array:')
print(arr1)
print('shape of the array:',arr1.shape)
print('Dimensions of the array:',arr1.ndim)

arr2 = np.array([[[1,2,3],[4,5,6]]])
print('2nd Array:')
print(arr2)
print('shape of the array:',arr2.shape)
print('Dimensions of the array:',arr2.ndim)

1st Array:
[[1 2 3]
 [4 5 6]]
shape of the array: (2, 3)
Dimensions of the array: 2
2nd Array:
[[[1 2 3]
  [4 5 6]]]
shape of the array: (1, 2, 3)
Dimensions of the array: 3


#6. Explain Data Analysis in your own words using a markdown cell.

Data analysis is the process of collecting, cleaning, and analysing data to extract useful information and identify patterns. It involves using tools such as Python and NumPy to perform calculations, analyze datasets (which can be read using Pandas), and support data-driven decision making.

In [ ]:
#Creation of numpy with different methods

In [5]:
arr1 = np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
arr1 = np.zeros([3,3])
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr1 = np.array([5, 10, 15, 20, 25])
print('Size of the array:',arr1.size)
print("Item size:", arr1.itemsize)
print("Total bytes used:", arr1.nbytes)

Size of the array: 5
Item size: 8
Total bytes used: 40


In [8]:
arr1 = np.linspace(0,14,7)
print(arr1)

[ 0.          2.33333333  4.66666667  7.          9.33333333 11.66666667
 14.        ]


In [9]:
arr1 = np.eye(4)
print(arr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
arr1 = np.diag([1,2,3])
print(arr1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
arr1 = np.full((2,3),9)
print(arr1)

[[9 9 9]
 [9 9 9]]


In [12]:
arr1 = np.random.rand(3,3)
print(arr1)

[[0.44720391 0.18365251 0.06145388]
 [0.84329811 0.14520493 0.93475844]
 [0.07085101 0.02336433 0.59896523]]


In [13]:
arr1 = np.random.randint(10,50,(4,4))
print(arr1)

[[38 31 24 39]
 [39 19 31 26]
 [25 41 22 28]
 [28 13 17 34]]


In [14]:
arr1 = np.random.randn(5)
print(arr1)

[ 0.9647238  -1.51287052 -0.54940692  0.63156138 -1.45011076]


In [15]:
arr1 = np.random.uniform(-5,5,(2,4))
print(arr1)

[[ 4.79200137 -3.0440495   0.49754814 -4.87157904]
 [-2.18869993  4.51248049 -1.87015084  4.45613822]]


In [16]:
arr1 = np.array([10, 20, 30, 40, 50])
arr1[2] = 35

print(arr1)

[10 20 35 40 50]


In [17]:
arr1 = np.arange(1, 13).reshape(3, 4)
print(arr1)

print('Second row:',arr1[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row: [5 6 7 8]


In [18]:
print('all elements in the last column:',arr1[:,-1])

all elements in the last column: [ 4  8 12]


In [19]:
arr1 = np.ones([3,3])
print('Original array:')
print(arr1)

arr2 = arr1.astype(int)
print('After changing datatype:')
print(arr2)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
After changing datatype:
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [20]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1*2)

[ 2  4  6  8 10]


In [21]:
#Numpy Methods

In [22]:
arr1 = np.arange(1,11)
print('Array:')
print(arr1)

print(arr1[2],arr1[5],arr1[7])

Array:
[ 1  2  3  4  5  6  7  8  9 10]
3 6 8


In [23]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[2:6])

[30 40 50 60]


In [24]:
arr = np.random.randint(1,20,10)
print('Array:',arr)
print(arr[arr>10])

Array: [ 4 14 15  5  9  8 14  2 19 10]
[14 15 14 19]


In [25]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [26]:
arr[1] = 99

print(arr)

[ 0 99  2  3  4  5]


In [27]:
arr[2:5] = 0

print(arr)

[ 0 99  0  0  0  5]


In [28]:
arr[-3:] = 10

print(arr)

[ 0 99  0 10 10 10]


In [29]:
arr = np.array([[1,2,3],[4,5,6]])
print('Original array:')
print(arr)
arr[1][1] = 100
print('After updation:')
print(arr)

Original array:
[[1 2 3]
 [4 5 6]]
After updation:
[[  1   2   3]
 [  4 100   6]]


In [30]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
arr[1] = 5
print(arr)

[[1 2 3]
 [5 5 5]
 [7 8 9]]


In [32]:
arr[:,-1] = [8,9,10]
print(arr)

[[ 1  2  8]
 [ 5  5  9]
 [ 7  8 10]]


In [33]:
arr[arr<5] = 100

print(arr)

[[100 100   8]
 [  5   5   9]
 [  7   8  10]]


In [34]:
arr = np.random.randint(1,21,10)
print(arr)

[15  6  2  4 17  1  1  3 17  8]


In [35]:
arr[arr>10] = 0
print(arr)

[0 6 2 4 0 1 1 3 0 8]


In [36]:
arr = np.array([10, 20, 30, 40])

arr = np.insert(arr,2,25)

print(arr)

[10 20 25 30 40]


In [37]:
arr = np.array([1,2,3])
arr = np.append(arr,[4,5,6])
print(arr)

[1 2 3 4 5 6]


In [38]:
arr = np.array([5, 10, 15, 20, 25])

arr = np.delete(arr,2)

print(arr)

[ 5 10 20 25]


In [39]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
arr = np.array([[1,2,3],[4,5,6]])
print('Original array:')
print(arr)
r = arr.ravel()
print('After using ravel, new array:',r)
r[2] = 100
print('Updation in the new array:',r)
print('Original array becomes:')
print(arr)
print('Here, Original array also gets affected')

Original array:
[[1 2 3]
 [4 5 6]]
After using ravel, new array: [1 2 3 4 5 6]
Updation in the new array: [  1   2 100   4   5   6]
Original array becomes:
[[  1   2 100]
 [  4   5   6]]
Here, Original array also gets affected


In [41]:
arr = np.array([[1,2,3],[4,5,6]])
print('Original array:')
print(arr)
r = arr.flatten()
print('After flattening, new array:',r)
r[2] = 100
print('Updation in the new array:',r)
print('Original array becomes:')
print(arr)
print('Here, Original array doesnot get affected')

Original array:
[[1 2 3]
 [4 5 6]]
After flattening, new array: [1 2 3 4 5 6]
Updation in the new array: [  1   2 100   4   5   6]
Original array becomes:
[[1 2 3]
 [4 5 6]]
Here, Original array doesnot get affected


In [42]:
arr = np.arange(1,10).reshape(3,3)
print('Original array:')
print(arr)
t = np.transpose(arr)
print('After transposing:')
print(t)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After transposing:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Create two arrays

In [43]:
A = np.array([2, 4, 6])
B = np.array([1, 2, 3])

In [44]:
print('Addition:',A+B)
print('Subtraction:',A-B)
print('Multiplication:',A*B)
print('Division:',A/B)

Addition: [3 6 9]
Subtraction: [1 2 3]
Multiplication: [ 2  8 18]
Division: [2. 2. 2.]


In [45]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print('dot product using Numpy:')
print(np.dot(A,B))

print('Matrix multiplication:')
print(A@B)

dot product using Numpy:
[[19 22]
 [43 50]]
Matrix multiplication:
[[19 22]
 [43 50]]


In [46]:
arr = np.array([4, 8, 15, 16, 23, 42])
print(arr)

[ 4  8 15 16 23 42]


In [47]:
print('Array:',arr)
print('Sum:',np.sum(arr))
print('Min:',np.min(arr))
print('Max:',np.max(arr))
print('Mean:',np.mean(arr))
print('Median:',np.median(arr))
print('Variance:',np.var(arr))
print('Standard Deviation:',np.std(arr))
print('correlation coefficient:',np.corrcoef(arr))

Array: [ 4  8 15 16 23 42]
Sum: 108
Min: 4
Max: 42
Mean: 18.0
Median: 15.5
Variance: 151.66666666666666
Standard Deviation: 12.315302134607444
correlation coefficient: 1.0


In [48]:
#NumPy Vectorization

In [49]:
arr = np.arange(1,11)
new = arr*5
print(new)

[ 5 10 15 20 25 30 35 40 45 50]


In [50]:
A = np.array([1, 2, 3, 4])
B = np.array([10, 20, 30, 40])
print('Sum:',A+B)

Sum: [11 22 33 44]


In [51]:
arr = np.arange(1,11)
print('Original array:',arr)
arr[arr%2==0] = 0
print('After replacing all even numbers with 0:',arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
After replacing all even numbers with 0: [1 0 3 0 5 0 7 0 9 0]


In [52]:
#Vectorization vs Loops

In [53]:
arr = np.array([1,2,3,4,5])

print('Using a for loop:')
for i in arr:
    sq = i**2
    print(sq,end = ' ')
print(end='\n')

print('Using NumPy Vectorization:')
arr1 = arr**2
print(arr1)

print('NumPy Vectorization takes less number of lines and easier code to write.')

Using a for loop:
1 4 9 16 25 
Using NumPy Vectorization:
[ 1  4  9 16 25]
NumPy Vectorization takes less number of lines and easier code to write.


In [54]:
arr = np.random.randint(0,11,10)
print('Array:',arr)

count=0
for i in arr:
    if i>5:
        count += 1
    else:
        pass
print('Count using for loop:',count)

count_vec = np.sum(arr > 5)
print("Count using vectorization:", count_vec)

Array: [8 1 7 2 2 6 6 1 1 0]
Count using for loop: 4
Count using vectorization: 4
