### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
### code here
import numpy as np

print('Original array:')
arr = np.array([
    [3.0,  2.0,  np.nan, 1.0],
    [10.0, 12.0, 10.0,   9.0],
    [5.0,  np.nan, 1.0,  np.nan]
])
print(arr)
print()
print('Find the missing data of the said array:')
print(np.isnan(arr))

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [2]:
### code here 
A = np.array([1, 2, 3, 4])
print('Array-1')
print(A)
B = np.array([1, 2, 3, 5])
print('Array-2')
print(B)

print('Element wise equality:')
result = np.equal(A, B)
print(result)

Array-1
[1 2 3 4]
Array-2
[1 2 3 5]
Element wise equality:
[ True  True  True False]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [3]:
## code here
print('Original array:')
arr = np.arange(0,16).reshape(4,4)
print(arr)
print()
print('New array after swapping first and last rows of the said array:')
temp = arr[0].copy()
arr[0] = arr[-1]
arr[-1] = temp
print(arr)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [4]:
#### code here
list1 = [1,2,3,4]
print('Original list:')
print(list1)
arr1 = np.array(list1)
print('After converting list into array:')
print(arr1)

tuple1 = (5,6,7,8)
print('Original Tuple:')
print(tuple1)
arr2 = np.array(tuple1)
print('After converting tuple into array:')
print(arr2)

Original list:
[1, 2, 3, 4]
After converting list into array:
[1 2 3 4]
Original Tuple:
(5, 6, 7, 8)
After converting tuple into array:
[5 6 7 8]


###### 5. Write a NumPy program to find common values between two arrays.

In [5]:
### code here
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,4,9,3])
common = arr1[np.isin(arr1, arr2)]
print(common)

[1 3 4]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [6]:
### code here
arr = np.array([[1,2],[3,4],[5,6]])
print('Reshape 3x2:')
print(arr)
print('Reshape 2x3:')
print(arr.reshape(2,3))

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [7]:
### code here
print('Original array:')
arr = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print(arr)

values = np.unique(arr)
counts = []

for v in values:
    count = 0
    for x in arr:
        if x == v:
            count += 1
    counts.append(count)

print('Frequency of unique values of the said array:')
print(np.array([values, counts]))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [8]:
### code here
print('Original arrays:')
print('Array-1')
arr1 = np.array([[0,0,0],[1,2,3],[4,5,6]])
print(arr1)
arr2 = np.array([10,11,12])
print('Array-2')
print(arr2)
print()
print('New Array:')
print(arr1 + arr2)

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [9]:
### code here
arr = np.arange(0,16).reshape(4,4)
print('Original array:')
print(arr)
print()
print('Extracted data: Second row')
print(arr[1])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [10]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [11]:
## code here
arr = np.arange(0,16).reshape(4,4)
print('Original array:')
print(arr)
print()
print('Extracted data: Third and fourth elements of the first and second rows')
print(arr[:2,2:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [12]:
### code here

today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2026-01-26
Today: 2026-01-27
Tomorrow: 2026-01-28


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [13]:
## code here
print('First Monday in May 2017:')
print(np.busday_offset('2017-05-01', 0, roll='forward', weekmask='Mon'))

First Monday in May 2017:
2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
